[compiler] Don't call UpdateMaxPushedArgumentCount on negative delta
This commit https://crrev.com/c/8128082 has started failing mjsunit/regress/wasm/regress-crbug-1465386 on ppc64:
```
wasm-function[1]:0x102: RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
```

The issue seems to be due to calling this function with a negative
delta.
- A caller is pushing 5 params to the stack
- A callee is pushing 0 params to the stack
- delta become -5 (0xFFFFFFFFFFFFFFFB)
- UpdateMaxPushedArgumentCount turns it into a large unsigned value
- Later it gets truncated to uint32 which become ~4GB which causes the stack check to always report overflow.

This seems to only be happening on platforms with separate Simd and Fp
registers (i.e ppc64) which allow for 0 register spills by the callee.

Change-Id: Ib3bd0cf87901f2aa28da6dec03ca592e52576c52
Reviewed-on: https://chromium-review.googlesource.com/c/v8/v8/+/8128870
Reviewed-by: Thibaud Michaud <thibaudm@chromium.org>
Commit-Queue: Milad Farazmand <mfarazma@ibm.com>
Cr-Commit-Position: refs/heads/main@{#108846}